### ISSUE TITLE
What to do to get fbgrab to be able to take screenshot from a different tty?

### ISSUE THREAD

**Issue by ragnarov** [jwilk/fbcat#20]
I do not understand what to do with 'CAP_SYS_TTY_CONFIG' ?
I did this (as root):
```
setcap 'cap_sys_tty_config+ep' /usr/bin/fbgrab
```
But then I get this:
```
$ fbgrab -c 3 meow.png
Couldn't get a file descriptor referring to the console.
```

**Comment by jwilk** [comment]
> ```
> setcap 'cap_sys_tty_config+ep' /usr/bin/fbgrab
> ```

fbgrab is a shell script. I don't think setting capabilities on scripts does anything useful.
Even if it did, this still wouldn't help, because the capapibilty wouldn't be inherited by `chvt`, which is the program that does VT switching.
You need to run setcap against `/bin/chvt`.

> ```
> $ fbgrab -c 3 meow.png
> Couldn't get a file descriptor referring to the console.
> ```

However, this error is not because of missing `CAP_SYS_TTY_CONFIG`.
It's because stdin in not a VT, so `chvt` tries to open `/dev/tty0` and various similar devices, and that fails.

I suppose you could try:
```console
$ fbgrab -c 3 meow.png < /dev/tty3
```
or
```console
$ fbgrab -c 3 meow.png < /dev/$(cat /sys/class/tty/tty0/active)
```

**Comment by ragnarov** [comment]
```
fbgrab -c 3 meow.png
```
This did work as root.

The following do not work as non-root:
```
fbgrab -c 3 meow.png < /dev/tty3
```
Here is the output:
```
$ fbgrab -c 3 meow.png < /dev/tty2
chvt: Couldn't activate vt 3: Operation not permitted
```
Also, there is no way of taking screenshot without changing vt ?

**Comment by jwilk** [comment]
> ```
> $ fbgrab -c 3 meow.png < /dev/tty2
> chvt: Couldn't activate vt 3: Operation not permitted
> ```

Works for me if I give `chvt` the `CAP_SYS_TTY_CONFIG` capability:
```console
$ fbgrab -c 3 meow.png < /dev/tty3
chvt: Couldn't activate vt 3: Operation not permitted
$ sudo setcap 'cap_sys_tty_config+ep' $(command -v chvt)
$ fbgrab -c 3 meow.png < /dev/tty3 && file meow.png
meow.png: PNG image data, 1280 x 1024, 2-bit colormap, non-interlaced
```
> Also, there is no way of taking screenshot without changing vt ?

I'm not aware of any way to do that.

OK, I guess you could extract text and colors using `/dev/vcsaN`, extract font info using the `GIO_FONTX` ioctl, and synthesize a screenshot from that.
I don't intend to implent the above in fbcat. It probably should be a seperate program anyway.

**Comment by ragnarov** [comment]
Thanks man.
